emoji_server_ids = [552249406808653836, 1109251867051044994, 1189295652518232155, 1162759875667964005, 1235129674485600276, 1323238503940755466] # emoji will be looked up by name from these servers only
train_types = [
	# possible options for matching, not provided = matches all
	# { type = "IC", line = "1",  line_startswith = "1", network = "SBB"}
	# possible options for display
	# { emoji = "ica|ic1", color = "#ff0404", hide_line_number = true, always_show_train_number = true }
	# ===== bri'ish =======
	{ network = "UK", line = "Bakerloo", emoji = "tflbakerloo", color = "#a65a2a", class = "britain" },
	{ network = "UK", line = "Central", emoji = "tflcentral", color = "#e1251b", class = "britain" },
	{ network = "UK", line = "Circle", emoji = "tflcircle", color = "#ffcd00", class = "britain" },
	{ network = "UK", line = "District", emoji = "tfldistrict", color = "#007934", class = "britain" },
	{ network = "UK", type = "STR", line = "DLR", emoji = "tfldlr", color = "#00afaa", class = "britain" },
	{ network = "UK", type = "Elizabeth", line = "line", emoji = "tflelizabeth", color = "#773dbd", class = "britain" },
	{ network = "UK", line = "Hammersmith & City", emoji = "tflhc", color = "#ec9bad", class = "britain" },
	{ network = "UK", line = "Jubilee", emoji = "tfljubilee", color = "#7a868c", class = "britain" },
	{ network = "UK", line = "Metropolitan", emoji = "tflmetropolitan", color = "#8a0b53", class = "britain" },
	{ network = "UK", line = "Northern", emoji = "tflnorthern", color = "#000000", class = "britain" },
	{ network = "UK", line = "Piccadilly", emoji = "tflpiccadilly", color = "#000f9f", class = "britain" },
	{ network = "UK", line = "Victoria", emoji = "tflvictoria", color = "#00a0df", class = "britain" },
	{ network = "UK", line = "Waterloo & City", emoji = "tflwc", color = "#6bcdb2", class = "britain" },
	{ network = "UK", type = "Overground", emoji = "tfloverground", color = "#ee7623", class = "britain" },
	{ network = "UK", fallback = true, emoji = "br0|br1", color = "#ff0000", class = "britain" },
	# ===== DB HAFAS provided train types =====
	{ type = "A", emoji = "A_", color = "#f49100", class="special" },
	{ type = "AST", emoji = "ast", color = "#ffd700", class="city transit" },
	# network = "CTS": strasbourg high-frequency buses
	{ type = "Bus", network = "CTS", line = "G", emoji = "Bus2|ctsG", color = "#f6c900", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "H", emoji = "Bus2|ctsH", color = "#a62341", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "C1", emoji = "Bus2|ctsC1", color = "#22ae84", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "C3", emoji = "Bus2|ctsC3", color = "#9fc204", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "C6", emoji = "Bus2|ctsC6", color = "#7d5d9f", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "C7", emoji = "Bus2|ctsC7", color = "#008a27", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "C8", emoji = "Bus2|ctsC8", color = "#88cdd5", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "C9", emoji = "Bus2|ctsC9", color = "#f26640", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "2", emoji = "Bus2|cts2", color = "#e10d19", hide_line_number = true },
	{ type = "Bus", network = "CTS", line = "4", emoji = "Bus2|cts4", color = "#cf0d1c", hide_line_number = true },
	{ type = "Bus", line_startswith = "N", emoji = "BusN", color = "#a3167e", class="city transit" },
	{ type = "Bus", line_startswith = "X", emoji = "BusX", remove_line_startswith = true, color = "#a3167e", class="city transit" },
	{ type = "Bus", emoji = "Bus", color = "#a3167e", class="city transit" },
	{ type = "CB", emoji = "cbc", color = "#c91432", class="special" },
	{ type = "CJX", emoji = "Ja|Jb", color = "#ff4f00", class="regional" },
	{ type = "D", emoji = "da|db", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "EC", emoji = "eca|ecb", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "ECE", emoji = "eca|ece", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "EIC", emoji = "pia|pib", color = "#ff0404", always_show_train_number = true, class="poland" },
	{ type = "EN", emoji = "na|nb", color = "#282559", always_show_train_number = true, class="long-distance 2" },
	{ type = "EST", emoji = "est0|est1", color = "#ff0404", always_show_train_number = true, class="long-distance 2" },
	{ type = "FA", emoji = "fa0|fa1", color = "#cccccc", always_show_train_number = true, class="long-distance 2" },
	{ type = "Fähre", emoji = "Faehre", color = "#00a4db", class="city transit" },
	{ type = "FB", emoji = "fb0|fb1", color = "#ff0404", always_show_train_number = true, class="long-distance 2" },
	{ type = "FEX", emoji = "fex0|fex1", color = "#ff4f00", class="regional" },
	{ type = "FLX", emoji = "La|Lb", color = "#72d800", always_show_train_number = true, class="long-distance 2" },
	{ type = "FR", emoji = "fr0|fr1", color = "#aa0000", always_show_train_number = true, class="long-distance 2" },
	{ type = "IR", line = "VAE", network = "CH-FV", emoji = "Ia|vae1|vae2|vae3|vae4|vae5", color = "#ff0404", always_show_train_number = true, hide_line_number = true },
	{ type = "IC", emoji = "ca|cb", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "ICD", emoji = "ca|icd1", color = "#ff0404", class="long-distance 2" },
	{ type = "ICE", emoji = "ca|Cb", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "ICN", emoji = "icn0|icn1", color = "#282559", always_show_train_number = true, class="long-distance 2" },
	{ type = "IR", emoji = "Ia|db", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "KM", emoji = "ka|kb", color = "#204a87", class="poland" },
	{ type = "KML", emoji = "kLa|kLb", color = "#204a87", class="poland" },
	{ type = "KS", emoji = "sa|sb", color = "#204a87", class="poland" },
	{ type = "L", emoji = "l0|Rb", color = "#204a87", class="regional" },
	{ type = "Lt", emoji = "lt0|lt1", class="special" },
	{ type = "M", emoji = "metro", color = "#014e8d", class="rapid transit" },
	{ type = "MEX", emoji = "m0|m1", color = "#204a87", class="regional" },
	{ type = "NJ", emoji = "Na|Nb", color = "#282559", always_show_train_number = true, class="long-distance 2" },
	{ type = "R", emoji = "Ra|Rb", color = "#204a87", class="regional" },
	{ type = "RB", emoji = "Ba|Bb", color = "#204a87", class="regional" },
	# network = "NS": matches if operator is "Nederlandse Spoorwegen"
	{ type = "RE", network = "NS", emoji = "ns0|ns1", color = "#204a87" },
	{ type = "RE", emoji = "Ea|Eb", color = "#ff4f00", class="regional" },
	{ type = "RER", emoji = "RER", color = "#2c8e4e", class="rapid transit" },
	{ type = "REX", emoji = "Ea|EXb", color = "#ff4f00", class="regional" },
	{ type = "RJ", emoji = "2a|2b", color = "#c63131", always_show_train_number = true, class="long-distance" },
	{ type = "RJX", emoji = "1a|1b", color = "#c63131", always_show_train_number = true, class="long-distance" },
	{ type = "RS", emoji = "rs0|rs1", color = "#2c8e4e", class="regional" },
	{ type = "RUF", emoji = "ruf", color = "#ffd700", class="city transit" },
	 # network = "AT": matches if station IDs start with 81…
	{ type = "S", network = "AT", emoji = "ATS", color = "#0096d8" },
	{ type = "S", network = "SWien", line = "1", emoji = "ATStrunk", color = "#fe90b5" },
	{ type = "S", network = "SWien", line = "2", emoji = "ATStrunk", color = "#fe90b5" },
	{ type = "S", network = "SWien", line = "3", emoji = "ATStrunk", color = "#fe90b5" },
	{ type = "S", network = "SWien", line = "4", emoji = "ATStrunk", color = "#fe90b5" },
	{ type = "S", network = "SWien", line = "7", emoji = "ATStrunk", color = "#fe90b5" },
	{ type = "S", network = "SWien", line = "45", emoji = "ATSgreen", color = "#bed643" },
	{ type = "S", network = "SWien", emoji = "ATS", color = "#0096d8" },
	# network = "AVG": matches if operator is "Albtal-Verkehrs-Gesellschaft mbH"
	{ type = "S", network = "AVG", emoji = "KAS", color = "#c5161c" },
	{ type = "S", line_startswith = "L", emoji = "SL", remove_line_startswith = true, color = "#c5161c", class="special" },
	{ type = "S", line_startswith = "N", emoji = "SN", color = "#c5161c", class="special" },
	{ type = "S", emoji = "SBahn", color = "#2c8e4e", class="rapid transit" },
	{ type = "SB", emoji = "SB", color = "#014e8d", class="city transit" },
	{ type = "Schw-B", emoji = "SchwB", color = "#014e8d", class="city transit" },
	{ type = "SEV", emoji = "Sa|Sb", class="special" },
	# network = "CTS": matches if operator is "CTS"
	{ type = "STR", network = "CTS", line = "A", emoji = "str2|ctsa", color = "#e10d19", hide_line_number = true },
	{ type = "STR", network = "CTS", line = "B", emoji = "str2|ctsb", color = "#009ee0", hide_line_number = true },
	{ type = "STR", network = "CTS", line = "C", emoji = "str2|ctsc", color = "#f29400", hide_line_number = true },
	{ type = "STR", network = "CTS", line = "D", emoji = "str2|ctsd", color = "#009933", hide_line_number = true },
	{ type = "STR", network = "CTS", line = "E", emoji = "str2|ctse", color = "#9085ba", hide_line_number = true },
	{ type = "STR", network = "CTS", line = "F", emoji = "str2|ctsf", color = "#97bf0d", hide_line_number = true },
	# network = "RNV": matches if operator starts with "Rhein-Neckar-Verkehr"
	{ type = "STR", network = "RNV", line = "1", emoji = "str2|rnv1", color = "#f39b9b", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "2", emoji = "str2|rnv2", color = "#b10346", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "3", emoji = "str2|rnv3", color = "#d6ad00", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "4", emoji = "str2|rnv4", color = "#e30613", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "4A", emoji = "str2|rnv4a", color = "#e30613", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "5", emoji = "str2|rnv5", color = "#00975f", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "5A", emoji = "str2|rnv5a", color = "#00975f", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "6", emoji = "str2|rnv6", color = "#966c29", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "6A", emoji = "str2|rnv6a", color = "#966c29", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "7", emoji = "str2|rnv7", color = "#ffcc00", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "8", emoji = "str2|rnv8", color = "#e17500", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "9", emoji = "str2|rnv9", color = "#95c23d", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "10", emoji = "str2|rnv10", color = "#a71680", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "15", emoji = "str2|rnv15", color = "#f7ab64", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "16", emoji = "str2|rnv16", color = "#5f6caf", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "21", emoji = "str2|rnv21", color = "#e30613", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "22", emoji = "str2|rnv22", color = "#fdc300", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "23", emoji = "str2|rnv23", color = "#e48f00", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "24", emoji = "str2|rnv24", color = "#8d2176", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "25", emoji = "str2|rnv25", color = "#95c23d", hide_line_number = true  },
	{ type = "STR", network = "RNV", line = "26", emoji = "str2|rnv26", color = "#f39b9b", hide_line_number = true  },
	# fix for Stuttgart Stadtbahn lines having a U prefix in the line
	{ type = "STB", line_startswith = "U", emoji = "STB", remove_line_startswith = true, color = "#c5161c", class="rapid transit" },
	# network = "Ü": Stadtbahn Hannover
	{ type = "STB", network = "Ü", emoji = "UE", color = "#20ac2b", class="rapid transit" },
	{ type = "STB", emoji = "STB", color = "#c5161c", class="rapid transit" },
	# network = "KVB": matches if inside geofence around Köln/Bonn
	# lines 61,62,65 are normal tram lines
	{ type = "STR", network = "KVB", line = "61", emoji = "tram", color = "#c5161c" },
	{ type = "STR", network = "KVB", line = "62", emoji = "tram", color = "#c5161c" },
	{ type = "STR", network = "KVB", line = "65", emoji = "tram", color = "#c5161c" },
	{ type = "STR", network = "KVB", emoji = "STB", color = "#c5161c" },
	{ type = "STR", emoji = "tram", color = "#c5161c", class="city transit" },
	{ type = "TER", emoji = "ta|tb", color = "#204a87", class="regional" },
	{ type = "TGV", emoji = "Ta|Tb", color = "#ff0404", always_show_train_number = true, class="long-distance" },
	{ type = "TLK", emoji = "tla|tlb", color = "#ff0404", always_show_train_number = true, class="poland" },
	# network = "BVG": matches if inside geofence around Berlin
	{ type = "U", line = "1", network = "BVG", emoji = "UBerlin1", color = "#7dad4c", hide_line_number = true },
	{ type = "U", line = "2", network = "BVG", emoji = "UBerlin2", color = "#da421e", hide_line_number = true },
	{ type = "U", line = "3", network = "BVG", emoji = "UBerlin3", color = "#16683d", hide_line_number = true },
	{ type = "U", line = "4", network = "BVG", emoji = "UBerlin4", color = "#f0d722", hide_line_number = true },
	{ type = "U", line = "5", network = "BVG", emoji = "UBerlin5", color = "#7e5330", hide_line_number = true },
	{ type = "U", line = "6", network = "BVG", emoji = "UBerlin6", color = "#8c6dab", hide_line_number = true },
	{ type = "U", line = "7", network = "BVG", emoji = "UBerlin7", color = "#528dba", hide_line_number = true },
	{ type = "U", line = "8", network = "BVG", emoji = "UBerlin8", color = "#224f86", hide_line_number = true },
	{ type = "U", line = "9", network = "BVG", emoji = "UBerlin9", color = "#f3791d", hide_line_number = true },
	{ type = "U", line = "12", network = "BVG", emoji = "UBerlin12", color = "#7dad4c", hide_line_number = true },
	# network = "HHA": matches if inside geofence around Hamburg
	{ type = "U", line = "1", network = "HHA", emoji = "UHH1", color = "#0073c0", hide_line_number = true },
	{ type = "U", line = "2", network = "HHA", emoji = "UHH2", color = "#ff2e17", hide_line_number = true },
	{ type = "U", line = "3", network = "HHA", emoji = "UHH3", color = "#ffd939", hide_line_number = true },
	{ type = "U", line = "4", network = "HHA", emoji = "UHH4", color = "#00b2b1", hide_line_number = true },
	# network = "MVG": matches if inside geofence around München
	{ type = "U", line = "1", network = "MVG", emoji = "UM1", color = "#447335", hide_line_number = true },
	{ type = "U", line = "2", network = "MVG", emoji = "UM2", color = "#bb0534", hide_line_number = true },
	{ type = "U", line = "3", network = "MVG", emoji = "UM3", color = "#e4692a", hide_line_number = true },
	{ type = "U", line = "4", network = "MVG", emoji = "UM4", color = "#35aa83", hide_line_number = true },
	{ type = "U", line = "5", network = "MVG", emoji = "UM5", color = "#b87c0a", hide_line_number = true },
	{ type = "U", line = "6", network = "MVG", emoji = "UM6", color = "#2362ae", hide_line_number = true },
	{ type = "U", line = "7", network = "MVG", emoji = "UM7", color = "#447335", hide_line_number = true },
	{ type = "U", line = "8", network = "MVG", emoji = "UM8", color = "#e4692a", hide_line_number = true },
	# network = "NRW": matches if inside geofence around NRW
	{ type = "U", network = "NRW", emoji = "STB", color = "#c5161c" },
	# network = "tl": matches if operator is "Transport publics de la Région Lausannoise"
	{ type = "U", line = "m1", network = "tl", emoji = "tlm1", color = "#ec008c", hide_line_number = true },
	{ type = "U", line = "m2", network = "tl", emoji = "tlm2", color = "#ec008c", hide_line_number = true },
	# network = "VAG": matches if inside geofence around Nürnberg
	{ type = "U", line = "1", network = "VAG", emoji = "UNbg1", color = "#176fc1", hide_line_number = true },
	{ type = "U", line = "2", network = "VAG", emoji = "UNbg2", color = "#ed1c24", hide_line_number = true },
	{ type = "U", line = "3", network = "VAG", emoji = "UNbg3", color = "#4cc3bc", hide_line_number = true },
	# network = "VGF": matches if inside geofence around Frankfurt (Main)
	{ type = "U", line = "1", network = "VGF", emoji = "uffm1", color = "#c52b1e", hide_line_number = true },
	{ type = "U", line = "2", network = "VGF", emoji = "uffm2", color = "#00ab4f", hide_line_number = true },
	{ type = "U", line = "3", network = "VGF", emoji = "uffm3", color = "#345aaf", hide_line_number = true },
	{ type = "U", line = "4", network = "VGF", emoji = "uffm4", color = "#fc5cac", hide_line_number = true },
	{ type = "U", line = "5", network = "VGF", emoji = "uffm5", color = "#0c7d3e", hide_line_number = true },
	{ type = "U", line = "6", network = "VGF", emoji = "uffm6", color = "#0082ca", hide_line_number = true },
	{ type = "U", line = "7", network = "VGF", emoji = "uffm7", color = "#f19e2d", hide_line_number = true },
	{ type = "U", line = "8", network = "VGF", emoji = "uffm8", color = "#ca7fbe", hide_line_number = true },
	{ type = "U", line = "9", network = "VGF", emoji = "uffm9", color = "#ffd939", hide_line_number = true },
	# network = "WL": matches if operator = "Wiener Linien"
	{ type = "U", line = "1", network = "WL", emoji = "UWien1", color = "#ed1d26", hide_line_number = true },
	{ type = "U", line = "2", network = "WL", emoji = "UWien2", color = "#9e50af", hide_line_number = true },
	{ type = "U", line = "3", network = "WL", emoji = "UWien3", color = "#f47114", hide_line_number = true },
	{ type = "U", line = "4", network = "WL", emoji = "UWien4", color = "#1ea366", hide_line_number = true },
	{ type = "U", line = "5", network = "WL", emoji = "UWien5", color = "#0098a1", hide_line_number = true },
	{ type = "U", line = "6", network = "WL", emoji = "UWien6", color = "#926131", hide_line_number = true },
	{ type = "U", line_startswith = "m", emoji = "metro", remove_line_startswith = true, color = "#c5161c", class="rapid transit" },
	{ type = "U", emoji = "U_", color = "#014e8d", class="rapid transit" },
	{ type = "WB", emoji = "wa|wb", color = "#2e86ce", class="long-distance 2" },
	{ type = "WLB", emoji = "wlb", color = "#175a97", class="special" },
	{ type = "ZahnR", emoji = "zahnr", class="city transit" },
	# network = "ST": matches if operator any of "Blauwnet", "Arriva Nederland", "RRReis", "R-net"
	{ type = "", network = "ST", emoji = "s0|s1", color = "#204a87" },
	# ===== manual checkin train types =====
	{ type = "bike", emoji = "sbbvelo", class="manual" },
	{ type = "boat", emoji = "sbbboot", class="manual" },
	{ type = "car", emoji = "sbbauto", class="manual" },
	{ type = "coach", emoji = "sbbcoach", class="manual" },
	{ type = "plane", emoji = "sbbflug", class="manual" },
	{ type = "steam", emoji = "sbbsteam", class="manual" },
	{ type = "walk", emoji = "sbbwalk", class="manual" },
	# ===== fallback for unknown train types =====
	{ emoji = "sbbzug", fallback = true }
]
[network_descriptions]
AT = "S-Bahn in Austria"
AVG = "Stadtbahn Karlsruhe"
BVG = "U-Bahn Berlin"
CH-FV = "Swiss long-distance trains"
CTS = "Strasbourg trams"
HHA = "U-Bahn Hamburg"
KVB = "Stadtbahn Köln/Bonn"
MVG = "U-Bahn München"
NRW = "Stadtbahn Rhein/Ruhr"
NS = "Nederlandse Spoorwegen Sprinter"
RNV = "Rhein-Neckar-Verkehr MA/LU/HD"
ST = "Stoptrein"
SWien = "S-Bahn Wien"
tl = "Metro Lausanne"
VAG = "U-Bahn Nürnberg"
VGF = "U-Bahn Frankfurt"
WL = "U-Bahn Wien"
"UK" = "Trains in britain"
"Ü" = "Stadtbahn Hannover"
