CREATE TABLE cts_stops(
	name TEXT,
	logicalstopcode INTEGER PRIMARY KEY
);

-- generated with
-- curl -X 'GET' 'https://api.cts-strasbourg.eu/v1/siri/2.0/stoppoints-discovery' -H 'accept: text/plain' -H "Authorization: Basic [the token and a trailing colon base64 encoded]" | jq -r '.StopPointsDelivery.AnnotatedStopPointRef[]|"insert or replace into cts_stops values(\'\\(.StopName|sub("\'"; "\'\'"))\', \\(.Extension.LogicalStopCode));"' | sort | uniq
-- regenerate as needed (rarely probably)
begin;
insert or replace into cts_stops values('23 Novembre', 704);
insert or replace into cts_stops values('Abattoirs', 10);
insert or replace into cts_stops values('Abbatiale', 11);
insert or replace into cts_stops values('Abbé de l''Epée', 12);
insert or replace into cts_stops values('Abbé Lemire', 13);
insert or replace into cts_stops values('Acacias', 14);
insert or replace into cts_stops values('Achenheim Ouest', 775);
insert or replace into cts_stops values('Aéroparc', 16);
insert or replace into cts_stops values('A l''Aigle', 17);
insert or replace into cts_stops values('Albert Schweitzer', 23);
insert or replace into cts_stops values('Allée de l''Euro', 19);
insert or replace into cts_stops values('Alouettes', 20);
insert or replace into cts_stops values('Alsace', 688);
insert or replace into cts_stops values('Alt Winmärik-Vieux Marché aux Vins', 24);
insert or replace into cts_stops values('Ampère', 660);
insert or replace into cts_stops values('Ancienne Forge', 28);
insert or replace into cts_stops values('Ancienne Synagogue / Les Halles', 30);
insert or replace into cts_stops values('Anémones', 27);
insert or replace into cts_stops values('Ankara', 29);
insert or replace into cts_stops values('Arago', 136);
insert or replace into cts_stops values('Aristide Briand', 32);
insert or replace into cts_stops values('Athènes', 716);
insert or replace into cts_stops values('Austerlitz', 755);
insert or replace into cts_stops values('Avenir', 37);
insert or replace into cts_stops values('Baggersee', 38);
insert or replace into cts_stops values('Baillis', 39);
insert or replace into cts_stops values('Bâle', 40);
insert or replace into cts_stops values('Ballastière', 41);
insert or replace into cts_stops values('Banlieue', 42);
insert or replace into cts_stops values('Barr', 43);
insert or replace into cts_stops values('Bartischgut', 44);
insert or replace into cts_stops values('Belzwoerth', 46);
insert or replace into cts_stops values('Benjamin Silliman Junior', 810);
insert or replace into cts_stops values('Bergerac', 47);
insert or replace into cts_stops values('Berlioz', 48);
insert or replace into cts_stops values('Berstett', 49);
insert or replace into cts_stops values('Bethel', 50);
insert or replace into cts_stops values('Bethesda', 51);
insert or replace into cts_stops values('Bischheim Gare', 52);
insert or replace into cts_stops values('Bitche', 54);
insert or replace into cts_stops values('Blaesheim', 55);
insert or replace into cts_stops values('Blaesheim Ouest', 737);
insert or replace into cts_stops values('Boecklin', 535);
insert or replace into cts_stops values('Boecklin', 57);
insert or replace into cts_stops values('Boeuf Rouge', 60);
insert or replace into cts_stops values('Bohrie', 58);
insert or replace into cts_stops values('Bois Fleuri', 59);
insert or replace into cts_stops values('Boulevard des Enseignes', 808);
insert or replace into cts_stops values('Boulogne', 739);
insert or replace into cts_stops values('Bourgogne', 63);
insert or replace into cts_stops values('Bouvreuils', 64);
insert or replace into cts_stops values('Brant Université', 69);
insert or replace into cts_stops values('Brasseurs', 795);
insert or replace into cts_stops values('Brême', 65);
insert or replace into cts_stops values('Broglie', 67);
insert or replace into cts_stops values('Bruche', 68);
insert or replace into cts_stops values('Bruxelles', 70);
insert or replace into cts_stops values('Bruxelles (Marché)', 70);
insert or replace into cts_stops values('Bugatti', 71);
insert or replace into cts_stops values('Bussière', 72);
insert or replace into cts_stops values('Camping', 36);
insert or replace into cts_stops values('Campus d''Illkirch', 75);
insert or replace into cts_stops values('Canal', 76);
insert or replace into cts_stops values('Capitainerie', 751);
insert or replace into cts_stops values('Capucins', 79);
insert or replace into cts_stops values('Carpe Haute', 74);
insert or replace into cts_stops values('CARSAT', 137);
insert or replace into cts_stops values('Catherine', 80);
insert or replace into cts_stops values('Centre de Traumatologie', 83);
insert or replace into cts_stops values('Centre Sportif', 82);
insert or replace into cts_stops values('Cerisiers', 81);
insert or replace into cts_stops values('Cervantès', 730);
insert or replace into cts_stops values('Chambre de métiers', 92);
insert or replace into cts_stops values('Chambre de Métiers', 92);
insert or replace into cts_stops values('Champ de Manoeuvre', 91);
insert or replace into cts_stops values('Chateaubriand', 86);
insert or replace into cts_stops values('Château d''Eau', 88);
insert or replace into cts_stops values('Cherbourg', 90);
insert or replace into cts_stops values('Cheval Blanc', 87);
insert or replace into cts_stops values('Chopin', 93);
insert or replace into cts_stops values('Cimetière Nord', 111);
insert or replace into cts_stops values('Cimetière Sud', 113);
insert or replace into cts_stops values('Cirque – Centre Equestre', 753);
insert or replace into cts_stops values('Citadelle', 756);
insert or replace into cts_stops values('Cité Administrative', 96);
insert or replace into cts_stops values('Cité de l''Ill', 99);
insert or replace into cts_stops values('Cité Meinau', 100);
insert or replace into cts_stops values('Cité Russi', 112);
insert or replace into cts_stops values('Cité Universitaire', 114);
insert or replace into cts_stops values('Clairvivre', 789);
insert or replace into cts_stops values('Clémenceau', 115);
insert or replace into cts_stops values('Clinique de l''Orangerie', 116);
insert or replace into cts_stops values('Clinique Sainte Anne', 117);
insert or replace into cts_stops values('CMCO', 118);
insert or replace into cts_stops values('Coehorn', 121);
insert or replace into cts_stops values('Collège Galilée', 123);
insert or replace into cts_stops values('Collège La Fontaine', 122);
insert or replace into cts_stops values('Collège Leclerc', 124);
insert or replace into cts_stops values('Collège Paul Emile Victor', 126);
insert or replace into cts_stops values('Colombes', 127);
insert or replace into cts_stops values('Colonel Lilly', 125);
insert or replace into cts_stops values('Colonne', 128);
insert or replace into cts_stops values('Colverts', 828);
insert or replace into cts_stops values('Commerce', 824);
insert or replace into cts_stops values('Comtes', 800);
insert or replace into cts_stops values('Conseil de l''Europe', 453);
insert or replace into cts_stops values('Conseil des Quinze', 131);
insert or replace into cts_stops values('Coopérative', 129);
insert or replace into cts_stops values('Copenhague', 720);
insert or replace into cts_stops values('Copernic', 130);
insert or replace into cts_stops values('Corbeau', 132);
insert or replace into cts_stops values('Cor de Chasse', 120);
insert or replace into cts_stops values('Coucou des Bois', 119);
insert or replace into cts_stops values('Couronne', 134);
insert or replace into cts_stops values('Cours de l''Illiade', 742);
insert or replace into cts_stops values('C.R.A.M.', 135);
insert or replace into cts_stops values('Cressier Château d''eau', 139);
insert or replace into cts_stops values('Croix', 141);
insert or replace into cts_stops values('Dalis', 142);
insert or replace into cts_stops values('Dante', 143);
insert or replace into cts_stops values('Danube Le Vaisseau', 144);
insert or replace into cts_stops values('Dauphiné', 145);
insert or replace into cts_stops values('De Gaulle', 147);
insert or replace into cts_stops values('De Lattre de Tassigny', 148);
insert or replace into cts_stops values('Denis Papin', 825);
insert or replace into cts_stops values('Dietterlin', 149);
insert or replace into cts_stops values('D''Nedergass', 151);
insert or replace into cts_stops values('Donon', 153);
insert or replace into cts_stops values('Dordogne', 154);
insert or replace into cts_stops values('Doubs', 155);
insert or replace into cts_stops values('Droits de l''Homme', 156);
insert or replace into cts_stops values('Ducs d''Alsace', 157);
insert or replace into cts_stops values('Dunkerque', 158);
insert or replace into cts_stops values('Duntzenheim', 159);
insert or replace into cts_stops values('Eckbolsheim Centre', 160);
insert or replace into cts_stops values('Eckbolsheim Mairie', 686);
insert or replace into cts_stops values('Eckbolsheim Parc d''Activités', 165);
insert or replace into cts_stops values('Eckwersheim Cimetière', 163);
insert or replace into cts_stops values('Eckwersheim Hippodrome', 164);
insert or replace into cts_stops values('Eckwersheim Mairie', 166);
insert or replace into cts_stops values('Ecole', 168);
insert or replace into cts_stops values('Ecoparc Rhénan', 811);
insert or replace into cts_stops values('Ecrivains', 169);
insert or replace into cts_stops values('Edmond Rostand', 723);
insert or replace into cts_stops values('Eglise Saint Florent', 710);
insert or replace into cts_stops values('Ehn', 172);
insert or replace into cts_stops values('Electricité', 770);
insert or replace into cts_stops values('Elisa', 173);
insert or replace into cts_stops values('Elmerforst', 174);
insert or replace into cts_stops values('Elsau', 175);
insert or replace into cts_stops values('Emailleries', 679);
insert or replace into cts_stops values('Embranchement', 678);
insert or replace into cts_stops values('Emile Mathis', 176);
insert or replace into cts_stops values('Entzheim Centre', 177);
insert or replace into cts_stops values('Entzheim Gare', 705);
insert or replace into cts_stops values('Entzheim Ouest', 179);
insert or replace into cts_stops values('Entzheim Parc', 462);
insert or replace into cts_stops values('Ermitage', 180);
insert or replace into cts_stops values('Eschau Mairie', 183);
insert or replace into cts_stops values('Espace Européen de l'' Entreprise', 182);
insert or replace into cts_stops values('Espérance', 184);
insert or replace into cts_stops values('Esplanade', 185);
insert or replace into cts_stops values('Etoile Bourse', 186);
insert or replace into cts_stops values('Etoile d''Or', 187);
insert or replace into cts_stops values('Etoile Polygone', 189);
insert or replace into cts_stops values('Eurofret', 190);
insert or replace into cts_stops values('Faisanderie', 196);
insert or replace into cts_stops values('Faisans', 192);
insert or replace into cts_stops values('Faubourg d''Alençon', 191);
insert or replace into cts_stops values('Faubourg de la Paix', 194);
insert or replace into cts_stops values('Faubourg de Pierre', 195);
insert or replace into cts_stops values('Faubourg de Saverne', 197);
insert or replace into cts_stops values('Faubourg National', 193);
insert or replace into cts_stops values('Fédération', 199);
insert or replace into cts_stops values('Fegersheim Mairie', 210);
insert or replace into cts_stops values('Fischacker', 213);
insert or replace into cts_stops values('Fleurs', 785);
insert or replace into cts_stops values('Floralies', 214);
insert or replace into cts_stops values('Foch', 215);
insert or replace into cts_stops values('Fondeur', 218);
insert or replace into cts_stops values('Fontaine', 784);
insert or replace into cts_stops values('Forges', 728);
insert or replace into cts_stops values('Forlen', 822);
insert or replace into cts_stops values('Fort Desaix', 216);
insert or replace into cts_stops values('Fort Lefèbvre', 748);
insert or replace into cts_stops values('Fort Louis', 217);
insert or replace into cts_stops values('Franche Comté', 223);
insert or replace into cts_stops values('François de Larderel', 809);
insert or replace into cts_stops values('Frères Eberts', 224);
insert or replace into cts_stops values('Frères Lumière', 225);
insert or replace into cts_stops values('Fuchs am Buckel', 227);
insert or replace into cts_stops values('Fusiliers Marins', 229);
insert or replace into cts_stops values('Futura Glacière', 228);
insert or replace into cts_stops values('Gaertel', 231);
insert or replace into cts_stops values('Gallia', 233);
insert or replace into cts_stops values('Gardes Forestiers', 232);
insert or replace into cts_stops values('Gare aux Marchandises', 718);
insert or replace into cts_stops values('Gare centrale', 230);
insert or replace into cts_stops values('Gare Centrale', 230);
insert or replace into cts_stops values('Garenne', 841);
insert or replace into cts_stops values('Geispolsheim Centre Commercial', 236);
insert or replace into cts_stops values('Geispolsheim Gare', 237);
insert or replace into cts_stops values('Geispolsheim Mairie', 241);
insert or replace into cts_stops values('Geispolsheim Ouest', 243);
insert or replace into cts_stops values('Geispolsheim Verdun', 646);
insert or replace into cts_stops values('Geispolsheim ZI', 244);
insert or replace into cts_stops values('Général de Gaulle', 238);
insert or replace into cts_stops values('Général Leclerc', 239);
insert or replace into cts_stops values('Général Lejeune', 240);
insert or replace into cts_stops values('Georges Burger', 235);
insert or replace into cts_stops values('Geroldseck', 712);
insert or replace into cts_stops values('Glaubitz', 245);
insert or replace into cts_stops values('Gliesberg', 246);
insert or replace into cts_stops values('Gloeckelsberg', 247);
insert or replace into cts_stops values('Golbery', 248);
insert or replace into cts_stops values('Goldschmidt', 249);
insert or replace into cts_stops values('Graffenstaden', 745);
insert or replace into cts_stops values('Graffenstaden Digue', 150);
insert or replace into cts_stops values('Graffenstaden Gare', 749);
insert or replace into cts_stops values('Graffenstaden Z.I', 255);
insert or replace into cts_stops values('Gravière Stade de la Meinau', 420);
insert or replace into cts_stops values('Grüber', 252);
insert or replace into cts_stops values('Grundgrübe', 253);
insert or replace into cts_stops values('Gutenberg', 762);
insert or replace into cts_stops values('Haldenbourg', 258);
insert or replace into cts_stops values('Hangenbieten Mairie', 829);
insert or replace into cts_stops values('Hay Ecomusée', 263);
insert or replace into cts_stops values('Hechner/Centre Funéraire', 264);
insert or replace into cts_stops values('Henri Frenay', 265);
insert or replace into cts_stops values('Herrade', 714);
insert or replace into cts_stops values('Herrenwasser', 266);
insert or replace into cts_stops values('Hetzlader', 267);
insert or replace into cts_stops values('Hieselrain', 268);
insert or replace into cts_stops values('Hirondelles', 269);
insert or replace into cts_stops values('Hochfelden', 733);
insert or replace into cts_stops values('Hochschule / Läger', 787);
insert or replace into cts_stops values('Hoenheim Gare', 274);
insert or replace into cts_stops values('Hoenheim Mairie', 281);
insert or replace into cts_stops values('Hohl', 279);
insert or replace into cts_stops values('Hohwart', 280);
insert or replace into cts_stops values('Holtzheim Centre', 270);
insert or replace into cts_stops values('Holtzheim Centre Marché', 270);
insert or replace into cts_stops values('Holtzheim Eglise', 734);
insert or replace into cts_stops values('Holtzheim Ouest', 283);
insert or replace into cts_stops values('Holtzheim ZA', 830);
insert or replace into cts_stops values('Homme de Fer', 275);
insert or replace into cts_stops values('Honau', 282);
insert or replace into cts_stops values('Hôpital Civil', 272);
insert or replace into cts_stops values('Hôpital de Hautepierre', 277);
insert or replace into cts_stops values('Hôtel de Police', 284);
insert or replace into cts_stops values('Hôtel du Département', 273);
insert or replace into cts_stops values('Icare', 288);
insert or replace into cts_stops values('Ile de France', 289);
insert or replace into cts_stops values('Illkirch Fort Uhrich', 221);
insert or replace into cts_stops values('Illkirch Lixenbuhl', 290);
insert or replace into cts_stops values('Illkirch Mairie', 291);
insert or replace into cts_stops values('Illkirch Parc d''Innovation', 736);
insert or replace into cts_stops values('Illkirch Parc d''Innovation (Terminus)', 736);
insert or replace into cts_stops values('Imprimeurs', 823);
insert or replace into cts_stops values('Ingold', 293);
insert or replace into cts_stops values('IUT  Pasteur', 294);
insert or replace into cts_stops values('IUT Pasteur', 294);
insert or replace into cts_stops values('Jacob', 295);
insert or replace into cts_stops values('Jacobi Netter', 727);
insert or replace into cts_stops values('Jacqueline', 724);
insert or replace into cts_stops values('Jardin des deux Rives', 752);
insert or replace into cts_stops values('Jardin des Roses', 297);
insert or replace into cts_stops values('Jardin des Vignes', 299);
insert or replace into cts_stops values('Jardiniers', 790);
insert or replace into cts_stops values('Jardins', 296);
insert or replace into cts_stops values('Jean Hermann', 793);
insert or replace into cts_stops values('Jean Jaures', 298);
insert or replace into cts_stops values('Jean Monnet', 300);
insert or replace into cts_stops values('Jean Perrin', 309);
insert or replace into cts_stops values('Jésuites', 308);
insert or replace into cts_stops values('Karine', 310);
insert or replace into cts_stops values('Kastler', 311);
insert or replace into cts_stops values('Kehl Bahnhof', 313);
insert or replace into cts_stops values('Kehl Rathaus', 786);
insert or replace into cts_stops values('Kepler', 726);
insert or replace into cts_stops values('Kibitzenau', 316);
insert or replace into cts_stops values('Kiefer', 317);
insert or replace into cts_stops values('Klebsau', 318);
insert or replace into cts_stops values('Kolbsheim Mairie', 831);
insert or replace into cts_stops values('Krimmeri Stade de la Meinau', 319);
insert or replace into cts_stops values('Krutenau', 320);
insert or replace into cts_stops values('Lac Achard', 840);
insert or replace into cts_stops values('Lac - Berne', 683);
insert or replace into cts_stops values('Lac - Soleure', 684);
insert or replace into cts_stops values('Laiterie', 323);
insert or replace into cts_stops values('Laiterie - Saales', 372);
insert or replace into cts_stops values('Lamartine', 325);
insert or replace into cts_stops values('Lamey', 326);
insert or replace into cts_stops values('Lampertheim Alisiers', 760);
insert or replace into cts_stops values('Lampertheim Eglise', 321);
insert or replace into cts_stops values('Lampertheim Mairie', 328);
insert or replace into cts_stops values('Landsberg', 329);
insert or replace into cts_stops values('Langstross/Grand Rue', 322);
insert or replace into cts_stops values('La Rochelle', 330);
insert or replace into cts_stops values('La Souffel', 331);
insert or replace into cts_stops values('Lauterbourg', 332);
insert or replace into cts_stops values('La Vigie', 333);
insert or replace into cts_stops values('Lavoisier', 719);
insert or replace into cts_stops values('La Wantzenau Ecole', 358);
insert or replace into cts_stops values('La Wantzenau Eglise', 359);
insert or replace into cts_stops values('La Wantzenau Gare', 360);
insert or replace into cts_stops values('La Wantzenau Le Golf', 361);
insert or replace into cts_stops values('La Wantzenau Le Tilleul', 364);
insert or replace into cts_stops values('La Wantzenau Mairie', 362);
insert or replace into cts_stops values('La Wantzenau ZA', 763);
insert or replace into cts_stops values('Lazaret', 334);
insert or replace into cts_stops values('Leclerc', 335);
insert or replace into cts_stops values('Le Corbusier', 337);
insert or replace into cts_stops values('Lefèbvre', 336);
insert or replace into cts_stops values('Le Galet', 731);
insert or replace into cts_stops values('Le Marais', 338);
insert or replace into cts_stops values('Lerchenberg', 339);
insert or replace into cts_stops values('Le Ried', 340);
insert or replace into cts_stops values('Les Halles - Pont de Paris', 341);
insert or replace into cts_stops values('Les Halles Sébastopol', 342);
insert or replace into cts_stops values('Liberté', 343);
insert or replace into cts_stops values('Lingolsheim Alouettes', 681);
insert or replace into cts_stops values('Lingolsheim Centre', 350);
insert or replace into cts_stops values('Lingolsheim Cimetière', 110);
insert or replace into cts_stops values('Lingolsheim Gare', 352);
insert or replace into cts_stops values('Lingolsheim Mairie', 353);
insert or replace into cts_stops values('Lingolsheim Tiergaertel', 348);
insert or replace into cts_stops values('Lipsheim Centre', 344);
insert or replace into cts_stops values('Lipsheim Est', 345);
insert or replace into cts_stops values('Lipsheim Gare', 346);
insert or replace into cts_stops values('Loeb', 354);
insert or replace into cts_stops values('Londres', 721);
insert or replace into cts_stops values('Lorient', 426);
insert or replace into cts_stops values('Lorraine', 702);
insert or replace into cts_stops values('Louis Ampère', 827);
insert or replace into cts_stops values('Louis Loucheur', 356);
insert or replace into cts_stops values('Lycée Couffignal', 366);
insert or replace into cts_stops values('Lycée Jean Monnet', 367);
insert or replace into cts_stops values('Lycée Kléber', 368);
insert or replace into cts_stops values('Lycée Marc Bloch', 369);
insert or replace into cts_stops values('Lycée Marcel Rudloff', 371);
insert or replace into cts_stops values('Lycée Marcel Rudloff', 797);
insert or replace into cts_stops values('Lycée Pasteur', 373);
insert or replace into cts_stops values('Madrid', 717);
insert or replace into cts_stops values('Maires Schaub', 387);
insert or replace into cts_stops values('Maison Rouge', 386);
insert or replace into cts_stops values('Maison Rouge (Rue de Wissembourg)', 386);
insert or replace into cts_stops values('Malterie', 380);
insert or replace into cts_stops values('Manège', 685);
insert or replace into cts_stops values('Marcel Pagnol', 381);
insert or replace into cts_stops values('Marcel Rudloff', 732);
insert or replace into cts_stops values('Marché Gare', 843);
insert or replace into cts_stops values('Marc Seguin', 388);
insert or replace into cts_stops values('Marguerite', 384);
insert or replace into cts_stops values('Maria Callas', 802);
insert or replace into cts_stops values('Marne', 385);
insert or replace into cts_stops values('Marne (déviation marché)', 385);
insert or replace into cts_stops values('Martin Schongauer', 412);
insert or replace into cts_stops values('Mathieu Zell', 709);
insert or replace into cts_stops values('Maxime Alexandre', 374);
insert or replace into cts_stops values('Mélanie', 791);
insert or replace into cts_stops values('Melina Mercouri', 803);
insert or replace into cts_stops values('Michel Ange', 392);
insert or replace into cts_stops values('Mittelhausbergen Eglise', 393);
insert or replace into cts_stops values('Mittelhausbergen Mittelberg', 394);
insert or replace into cts_stops values('Molkenbronn', 396);
insert or replace into cts_stops values('Montagne Verte', 410);
insert or replace into cts_stops values('Moser', 399);
insert or replace into cts_stops values('Moulin', 400);
insert or replace into cts_stops values('Mozart', 411);
insert or replace into cts_stops values('Mühlbach', 414);
insert or replace into cts_stops values('Mulhouse', 415);
insert or replace into cts_stops values('Mundolsheim Découvertes', 771);
insert or replace into cts_stops values('Mundolsheim Mairie', 416);
insert or replace into cts_stops values('Mundolsheim Parc', 780);
insert or replace into cts_stops values('Murhof', 417);
insert or replace into cts_stops values('Musau', 418);
insert or replace into cts_stops values('Musée d''Art Moderne', 375);
insert or replace into cts_stops values('Neudorf Marché', 421);
insert or replace into cts_stops values('Neuhof Corps Européen', 133);
insert or replace into cts_stops values('Neuhof Eglise', 423);
insert or replace into cts_stops values('Neuhof Ganzau', 424);
insert or replace into cts_stops values('Neuhof Lucie Aubrac', 425);
insert or replace into cts_stops values('Neuhof Rodolphe Reuss', 546);
insert or replace into cts_stops values('Neuhof Stockfeld', 427);
insert or replace into cts_stops values('Nid de Cigognes', 429);
insert or replace into cts_stops values('Niederbourg', 430);
insert or replace into cts_stops values('Niederhausbergen Centre', 432);
insert or replace into cts_stops values('Niederhausbergen Mairie', 431);
insert or replace into cts_stops values('Nord', 433);
insert or replace into cts_stops values('Oberhausbergen Eglise', 435);
insert or replace into cts_stops values('Oberhausbergen Est', 434);
insert or replace into cts_stops values('Oberhausbergen Mairie', 682);
insert or replace into cts_stops values('Obernai-Lyon', 436);
insert or replace into cts_stops values('Oberschaeffolsheim Mairie', 439);
insert or replace into cts_stops values('Observatoire', 438);
insert or replace into cts_stops values('Octroi', 441);
insert or replace into cts_stops values('Ohnheim Eglise', 442);
insert or replace into cts_stops values('Orangerie', 443);
insert or replace into cts_stops values('Orbey', 444);
insert or replace into cts_stops values('Orme', 445);
insert or replace into cts_stops values('Ostwald Bellevue', 447);
insert or replace into cts_stops values('Ostwald Eglise', 449);
insert or replace into cts_stops values('Ostwald Hôtel de Ville', 448);
insert or replace into cts_stops values('Paix', 457);
insert or replace into cts_stops values('Palais de la musique et des Congrès', 796);
insert or replace into cts_stops values('Palais des Fêtes', 454);
insert or replace into cts_stops values('Palerme', 458);
insert or replace into cts_stops values('Papeterie', 459);
insert or replace into cts_stops values('Parc de la Citadelle', 837);
insert or replace into cts_stops values('Parc des Romains', 799);
insert or replace into cts_stops values('Parc des sports', 715);
insert or replace into cts_stops values('Parc des Sports', 715);
insert or replace into cts_stops values('Parc des Tanneries', 801);
insert or replace into cts_stops values('Parc du Contades', 451);
insert or replace into cts_stops values('Parc Klinglin', 687);
insert or replace into cts_stops values('Parc Malraux', 743);
insert or replace into cts_stops values('Parc Wodli', 467);
insert or replace into cts_stops values('Parlement Européen', 464);
insert or replace into cts_stops values('Patronage', 466);
insert or replace into cts_stops values('Paul Eluard', 452);
insert or replace into cts_stops values('Perce Neige', 469);
insert or replace into cts_stops values('Perdrix', 470);
insert or replace into cts_stops values('Perdrix', 703);
insert or replace into cts_stops values('Petite', 472);
insert or replace into cts_stops values('Peupliers', 260);
insert or replace into cts_stops values('Pfister', 473);
insert or replace into cts_stops values('Phalsbourg', 474);
insert or replace into cts_stops values('Pigeons', 476);
insert or replace into cts_stops values('Place de l''Abattoir', 842);
insert or replace into cts_stops values('Place de Pierre', 485);
insert or replace into cts_stops values('Place des Romains', 486);
insert or replace into cts_stops values('Place de Wattwiller', 488);
insert or replace into cts_stops values('Place d''Islande', 706);
insert or replace into cts_stops values('Place d''Ostwald', 540);
insert or replace into cts_stops values('Plaine des Bouchers', 477);
insert or replace into cts_stops values('Plobsheim Canal', 481);
insert or replace into cts_stops values('Plobsheim Eglise', 482);
insert or replace into cts_stops values('Plobsheim Est', 483);
insert or replace into cts_stops values('Plobsheim Mairie', 484);
insert or replace into cts_stops values('Poincaré', 491);
insert or replace into cts_stops values('Pôle API', 735);
insert or replace into cts_stops values('Polygone', 700);
insert or replace into cts_stops values('Pont des Vosges', 512);
insert or replace into cts_stops values('Pont du Péage', 495);
insert or replace into cts_stops values('Pont Kuss', 492);
insert or replace into cts_stops values('Pont Phario', 496);
insert or replace into cts_stops values('Pont Schuhansen', 499);
insert or replace into cts_stops values('Pont S.N.C.F.', 500);
insert or replace into cts_stops values('Port Autonome Sud', 738);
insert or replace into cts_stops values('Port du Rhin', 517);
insert or replace into cts_stops values('Porte Blanche', 798);
insert or replace into cts_stops values('Porte de l''Hôpital', 520);
insert or replace into cts_stops values('Poteries', 725);
insert or replace into cts_stops values('Prés', 513);
insert or replace into cts_stops values('Presqu''ile André Malraux', 833);
insert or replace into cts_stops values('Protection', 515);
insert or replace into cts_stops values('Provence', 707);
insert or replace into cts_stops values('Prunelliers', 518);
insert or replace into cts_stops values('Pulverlaechel', 521);
insert or replace into cts_stops values('Quartier des Quinze', 522);
insert or replace into cts_stops values('Raisin d''Or', 523);
insert or replace into cts_stops values('Rathsamhausen', 524);
insert or replace into cts_stops values('Reichstett Rue de Paris', 794);
insert or replace into cts_stops values('Reichstett Vergers', 779);
insert or replace into cts_stops values('Rembrandt', 526);
insert or replace into cts_stops values('République', 527);
insert or replace into cts_stops values('Rhin', 528);
insert or replace into cts_stops values('Rhin Tortu', 529);
insert or replace into cts_stops values('Riehl', 532);
insert or replace into cts_stops values('Rieth', 533);
insert or replace into cts_stops values('Rives de l''Aar', 530);
insert or replace into cts_stops values('Robertsau Chasseurs', 536);
insert or replace into cts_stops values('Robertsau Eglise', 539);
insert or replace into cts_stops values('Robertsau Lamproie', 327);
insert or replace into cts_stops values('Robertsau L''Escale', 788);
insert or replace into cts_stops values('Robertsau Renaissance', 545);
insert or replace into cts_stops values('Robertsau Sainte Anne', 549);
insert or replace into cts_stops values('Rochechouart', 537);
insert or replace into cts_stops values('Rochefort', 740);
insert or replace into cts_stops values('Rodin', 538);
insert or replace into cts_stops values('Roethig Gare', 804);
insert or replace into cts_stops values('Rohmer', 541);
insert or replace into cts_stops values('Romains', 542);
insert or replace into cts_stops values('Rome', 543);
insert or replace into cts_stops values('Roseaux', 547);
insert or replace into cts_stops values('Rotonde', 550);
insert or replace into cts_stops values('Rotterdam', 839);
insert or replace into cts_stops values('Route de Hangenbieten', 832);
insert or replace into cts_stops values('Route de Wolfisheim', 554);
insert or replace into cts_stops values('Royan', 758);
insert or replace into cts_stops values('Rue d''Eckbolsheim', 559);
insert or replace into cts_stops values('Rue de Hoenheim', 563);
insert or replace into cts_stops values('Rue de la Gare', 562);
insert or replace into cts_stops values('Rue de l''Etang', 560);
insert or replace into cts_stops values('Rue de Mundolsheim', 566);
insert or replace into cts_stops values('Rue des Champs', 558);
insert or replace into cts_stops values('Rue des Charmilles', 826);
insert or replace into cts_stops values('Rue des Juifs', 564);
insert or replace into cts_stops values('Rue du Fort', 561);
insert or replace into cts_stops values('Saint-Antoine', 592);
insert or replace into cts_stops values('Saint Christophe', 596);
insert or replace into cts_stops values('Sainte Hélène', 610);
insert or replace into cts_stops values('Sainte Marguerite', 613);
insert or replace into cts_stops values('Saint Florent', 597);
insert or replace into cts_stops values('Saint-François', 598);
insert or replace into cts_stops values('Saint-Guillaume', 600);
insert or replace into cts_stops values('Saint-Ignace', 611);
insert or replace into cts_stops values('Saint-Junien', 612);
insert or replace into cts_stops values('Saint-Maurice', 614);
insert or replace into cts_stops values('Saint Nazaire', 615);
insert or replace into cts_stops values('Saint-Nicolas', 616);
insert or replace into cts_stops values('Saint Paul', 619);
insert or replace into cts_stops values('Saint Thomas Finkwiller', 620);
insert or replace into cts_stops values('Saint Yrieix', 623);
insert or replace into cts_stops values('Salm', 747);
insert or replace into cts_stops values('Saules', 781);
insert or replace into cts_stops values('Schaal', 570);
insert or replace into cts_stops values('Scheidstein', 571);
insert or replace into cts_stops values('Schiltigheim Campus', 713);
insert or replace into cts_stops values('Schiltigheim le Marais', 572);
insert or replace into cts_stops values('Schiltigheim Mairie', 574);
insert or replace into cts_stops values('Schluthfeld', 573);
insert or replace into cts_stops values('Schnokeloch', 575);
insert or replace into cts_stops values('Schott', 576);
insert or replace into cts_stops values('Schulmeister', 577);
insert or replace into cts_stops values('Sécurité Sociale', 583);
insert or replace into cts_stops values('Séné', 581);
insert or replace into cts_stops values('Shakespeare', 729);
insert or replace into cts_stops values('Soleil', 776);
insert or replace into cts_stops values('Souffelweyersheim Canal', 584);
insert or replace into cts_stops values('Souffelweyersheim Centre', 585);
insert or replace into cts_stops values('Souffelweyersheim Ecole', 586);
insert or replace into cts_stops values('Soultz', 589);
insert or replace into cts_stops values('Spesbourg', 782);
insert or replace into cts_stops values('Sports', 590);
insert or replace into cts_stops values('Square du Château', 591);
insert or replace into cts_stops values('Stade Vauban', 838);
insert or replace into cts_stops values('Starcoop', 757);
insert or replace into cts_stops values('Station de Pompage', 594);
insert or replace into cts_stops values('Stoskopf', 618);
insert or replace into cts_stops values('Stutzheim', 622);
insert or replace into cts_stops values('Tanneries', 624);
insert or replace into cts_stops values('Tauler', 626);
insert or replace into cts_stops values('Temple', 627);
insert or replace into cts_stops values('Terres de la Chapelle', 708);
insert or replace into cts_stops values('Titien', 630);
insert or replace into cts_stops values('Tobias Stimmer', 631);
insert or replace into cts_stops values('Touraine', 632);
insert or replace into cts_stops values('Travail', 633);
insert or replace into cts_stops values('Triage', 765);
insert or replace into cts_stops values('Tribunal - Fonderie', 635);
insert or replace into cts_stops values('Trois Epis', 634);
insert or replace into cts_stops values('Tuilerie', 805);
insert or replace into cts_stops values('Université', 638);
insert or replace into cts_stops values('Unterelsau', 637);
insert or replace into cts_stops values('Unterjaegerhof', 639);
insert or replace into cts_stops values('Urban', 750);
insert or replace into cts_stops values('Vanneaux', 640);
insert or replace into cts_stops values('Vendenheim Artisans', 31);
insert or replace into cts_stops values('Vendenheim Artisans', 778);
insert or replace into cts_stops values('Vendenheim au Tilleul', 648);
insert or replace into cts_stops values('Vendenheim Gare', 642);
insert or replace into cts_stops values('Vendenheim Mairie', 643);
insert or replace into cts_stops values('Verdon', 645);
insert or replace into cts_stops values('Verdun', 644);
insert or replace into cts_stops values('Vernois Mangold', 647);
insert or replace into cts_stops values('Victor Hugo', 650);
insert or replace into cts_stops values('Vienne', 722);
insert or replace into cts_stops values('Vieux Moulin', 651);
insert or replace into cts_stops values('Vignes', 746);
insert or replace into cts_stops values('Villa Vénitienne', 711);
insert or replace into cts_stops values('Virgile / Bosco', 61);
insert or replace into cts_stops values('Voltaire', 654);
insert or replace into cts_stops values('Vosges', 656);
insert or replace into cts_stops values('Vosges Oberlin', 655);
insert or replace into cts_stops values('Wacken', 657);
insert or replace into cts_stops values('Wagner', 701);
insert or replace into cts_stops values('Waldhorn', 658);
insert or replace into cts_stops values('Wasselonne', 659);
insert or replace into cts_stops values('Weeber', 661);
insert or replace into cts_stops values('Welsch', 662);
insert or replace into cts_stops values('Wibolsheim Chapelle', 663);
insert or replace into cts_stops values('Wihrel', 665);
insert or replace into cts_stops values('Wilson', 667);
insert or replace into cts_stops values('Winston Churchill', 664);
insert or replace into cts_stops values('Wissembourg', 668);
insert or replace into cts_stops values('Wolfisheim Mairie', 670);
insert or replace into cts_stops values('Wolfisheim Stade', 671);
insert or replace into cts_stops values('Ypres', 673);
insert or replace into cts_stops values('ZAC des Maréchaux', 783);
insert or replace into cts_stops values('Zénith', 689);
insert or replace into cts_stops values('Zone Commerciale Nord', 676);
insert or replace into cts_stops values('Zorn', 677);
insert or replace into cts_stops values('Zurich', 754);
commit;
